### ISSUE TITLE
Website copy edits

### ISSUE THREAD

**Issue by tcusher** [goinvo/HealthDataBasicsWebsite#5]
- On the first page, under “We Believe in Better”: individual is misspelled 
- On the “Process” page under item 2C there is an extra “the”: Craft the Story: "We explored concepts in greater detail, outlining frameworks and honing in on the **the** educational"
-  Under About, Kim McCleary (delete second L), Cynthia should have a comma before PhD, Taylor Cusher's title is now Associate Director

**Comment by jsonin** [comment]
Got it.
Will edit shortly.

**Comment by emorganball** [comment]
One more thing to add:
"Kim McCleary Senior Advisory" should be "Senior **Advisor". Also could you please move her to 3rd on the list (After Cynthia and Taylor)? 

Thanks!

**Comment by BrysonWong1** [comment]
Hi Team, We've made the first changes. I'm holding off until I check a couple things with our developer who's traveling until Monday on the 2nd ones.
